#!/bin/bash
# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
set -e

TESTDATA_DIR="$(dirname "$0")"
RUST_FILE="$TESTDATA_DIR/mod.rs"

if ! command -v ascii2der &> /dev/null; then
  echo "Please install https://github.com/google/der-ascii to run this script."
  exit 1
fi

cat <<EOF >"$RUST_FILE"
// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

//! Generated certificate test data.
//!
//! Do not edit this file by hand; regenerate it with
//! \`src/cert/testdata/generate.sh\` instead. You'll need to install the
//! https://github.com/google/der-ascii tool first.
EOF

rm -rf "$TESTDATA_DIR/der"
mkdir "$TESTDATA_DIR/der"
for ascii in $(find "$TESTDATA_DIR" -name '*.der'); do
  file="$(basename "${ascii%.*}")"
  cat "$ascii" | ascii2der > "$TESTDATA_DIR/der/$file.bin"
  cat <<EOF >>"$RUST_FILE"

#[rustfmt::skip]
/// Generated from $file.der.
pub const ${file^^}: untrusted::Input = untrusted::Input::from(include_bytes!("der/$file.bin"));
EOF
done

