  # NOTE: Autogenerated by {command}
  {message_type}:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz

    - name: Fuzz `{message_type}_request_from_wire`
      run: |
        cargo +nightly fuzz run \
          --release \
          --sanitizer address \
          {message_type}_request_from_wire \
          -- \
          -max_total_time=300
    - name: Fuzz `{message_type}_response_from_wire`
      run: |
        cargo +nightly fuzz run \
          --release \
          --sanitizer address \
          {message_type}_response_from_wire \
          -- \
          -max_total_time=180
    - name: Fuzz `{message_type}_request_to_wire`
      run: |
        cargo +nightly fuzz run \
          --release \
          --sanitizer address \
          {message_type}_request_to_wire \
          -- \
          -max_total_time=300
    - name: Fuzz `{message_type}_response_to_wire`
      run: |
        cargo +nightly fuzz run \
          --release \
          --sanitizer address \
          {message_type}_response_to_wire \
          -- \
          -max_total_time=180

