#!/usr/bin/env python3
# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

"""
Creates a new fuzz target for a given `manticore::protocol` message.

This script exists to minimize the boilerplate of doing so, seeing as such
targets tend to be quite simple.
"""

import argparse
import os
import sys
import re

SERIALIZE_TEMPLATE = """// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// NOTE: This file is autogenerated by:
// $ {command}

#![no_main]

use libfuzzer_sys::fuzz_target;

use manticore::protocol::Serialize;
use manticore::protocol::{module}::{typeid};

fuzz_target!(|data: {typename}| {{
    let mut out = [0u8; 1024];
    let _ = data.serialize(&mut &mut out[..]);
}});
"""

DESERIALIZE_TEMPLATE = """// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// NOTE: This file is autogenerated by:
// $ {command}

#![no_main]

use libfuzzer_sys::fuzz_target;

use manticore::protocol::Deserialize;
use manticore::protocol::{module}::{typeid};

fuzz_target!(|data: &[u8]| {{
    let mut data = data;
    let _ = {typename}::deserialize(&mut data);
}});
"""

def camel_to_snake(camel):
  """
  Convert `camel` to snake case.
  """
  return ''.join(['_' + c.lower() if c.isupper() else c for c in camel]).strip('_')

def append_to_file(filename, text):
  """
  Open or create `filename` and append `text` to it.
  """
  with open(filename, 'a') as f:
    f.write(text)

def add_target(fuzz_dir, name, rs_src):
  """
  Add a fuzz target named `name` with the given source file to the fuzzing
  directory `fuzz_dir`.

  If `name.rs` is present, the target is assumed to already be present.
  """
  target_rs = os.path.join(fuzz_dir, 'fuzz_targets', '{}.rs'.format(name))
  if os.path.exists(target_rs):
    return
  append_to_file(target_rs, rs_src)

  cargo_toml = os.path.join(fuzz_dir, 'Cargo.toml')
  append_to_file(cargo_toml,
"""
[[bin]]
name = "{target}"
path = "fuzz_targets/{target}.rs"
""".format(target=name))

def main():
  argparser = argparse.ArgumentParser(
    description=
    'Generates Deserialize/Serialize fuzz targets for a `manticore::protocol` '\
    'message.\n The type name of the message should be provided relative to '\
    '`manticore::protocol`.'
  )
  argparser.add_argument('typename',
                         type=str,
                         help='the name of the type to fuzz, such as '\
                              'firmware_version::FirmwareVersionRequest')
  argparser.add_argument('--target-templates',
                         type=str,
                         choices=['serialize', 'deserialize'],
                         nargs='*',
                         default=['serialize', 'deserialize'],
                         help='which target templates to use; defaults to all')
  argparser.add_argument('--fuzz-dir',
                         type=str,
                         default='fuzz',
                         help='the fuzzing directory, relative to the project'\
                              'root')
  args = argparser.parse_args()

  fuzz_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), args.fuzz_dir)
  (module, typename) = tuple(args.typename.split('::'))
  typeid = re.search('^\w+', typename)[0]  # Remove a trailing <'static>
  snake_case_name = camel_to_snake(typeid)
  command = ' '.join(sys.argv)

  if 'deserialize' in args.target_templates:
    deserialize_name = "{}_deserialize".format(snake_case_name)
    deserialize_src = DESERIALIZE_TEMPLATE.format(module=module,
                                                  typename=typename,
                                                  typeid=typeid,
                                                  command=command)
    add_target(fuzz_dir, deserialize_name, deserialize_src)

  if 'serialize' in args.target_templates:
    serialize_name = "{}_serialize".format(snake_case_name)
    serialize_src = SERIALIZE_TEMPLATE.format(module=module,
                                              typename=typename,
                                              typeid=typeid,
                                              command=command)
    add_target(fuzz_dir, serialize_name, serialize_src)

if __name__ == '__main__':
  main()
