// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

//! SHA-256, a cryptographic hash algorithm.

#[cfg(doc)]
use std::convert::Infallible;

/// A 256-bit message digest.
///
/// See [`Hasher`](trait.Hasher.html).
pub type Digest = [u8; 32];

/// An error returned by a SHA-256 function.
///
/// This type serves as a combination of built-in error types known to
/// Manticore, plus a "custom error" component for surfacing
/// implementation-specific errors that Manticore can treat as a black box.
///
/// This type has the benefit that, unlike a pure associated type, `From`
/// implementations for error-handling can be implemented on it.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Error<E = ()> {
    /// The "custom" error type, which is treated by Manticore as a black box.
    Custom(E),
}

impl<E> Error<E> {
    /// Erases the custom error type from this `Error`, replacing it with `()`.
    pub fn erased(self) -> Error {
        match self {
            Self::Custom(_) => Error::Custom(()),
        }
    }
}

/// A builder for creating new [`Hasher`]s.
///
/// A value of a type implementing this trait already contains everything it
/// needs (such as OS handles) to start creating hashers.
pub trait Builder {
    /// The concrete [`Hasher`] generated by this trait.
    type Hasher: Hasher;

    /// Begins a new hashing operation, returning a new [`Hasher`] to manage
    /// the computation.
    fn new_hasher(
        &self,
    ) -> Result<Self::Hasher, Error<<Self::Hasher as Hasher>::Error>>;

    /// Convenience function for hashing a contiguous buffer without having
    /// to deal with a hasher directly.
    fn hash_contiguous(
        &self,
        bytes: &[u8],
        out: &mut Digest,
    ) -> Result<(), Error<<Self::Hasher as Hasher>::Error>> {
        let mut hasher = self.new_hasher()?;
        hasher.write(bytes)?;
        hasher.finish(out)
    }
}

/// A particular hashing operation in progress.
///
/// Compare Rust's [`Hasher`] trait.
pub trait Hasher {
    /// A custom error type. If there isn't a meaningful one, use [`Infallible`].
    ///
    /// See [`Error`].
    type Error;

    /// Feeds more data into the current hashing operation.
    fn write(&mut self, bytes: &[u8]) -> Result<(), Error<Self::Error>>;

    /// Finishes the current hashing operation, writing the result to the given
    /// buffer.
    fn finish(self, out: &mut Digest) -> Result<(), Error<Self::Error>>;
}
