# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Fuzz Testing

on:
  schedule:
    - cron: '0 0 * * *'  # Midnight, daily.

env:
  CARGO_TERM_COLOR: always

jobs:
  # Everything below this line is generated and will be blown away by
  # fuzz/generate_fuzz_targets.py
  ## BEGIN GENERATED JOBS
  'manticore_protocol_capabilities_DeviceCapabilities__req_to_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::capabilities::DeviceCapabilities` with `req_to_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_capabilities_DeviceCapabilities__req_to_wire \
          -- -max_total_time=180

  'manticore_protocol_capabilities_DeviceCapabilities__req_from_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::capabilities::DeviceCapabilities` with `req_from_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_capabilities_DeviceCapabilities__req_from_wire \
          -- -max_total_time=180

  'manticore_protocol_capabilities_DeviceCapabilities__resp_from_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::capabilities::DeviceCapabilities` with `resp_from_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_capabilities_DeviceCapabilities__resp_from_wire \
          -- -max_total_time=180

  'manticore_protocol_capabilities_DeviceCapabilities__resp_to_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::capabilities::DeviceCapabilities` with `resp_to_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_capabilities_DeviceCapabilities__resp_to_wire \
          -- -max_total_time=180

  'manticore_protocol_device_id_DeviceId__req_to_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::device_id::DeviceId` with `req_to_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_device_id_DeviceId__req_to_wire \
          -- -max_total_time=180

  'manticore_protocol_device_id_DeviceId__req_from_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::device_id::DeviceId` with `req_from_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_device_id_DeviceId__req_from_wire \
          -- -max_total_time=180

  'manticore_protocol_device_id_DeviceId__resp_from_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::device_id::DeviceId` with `resp_from_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_device_id_DeviceId__resp_from_wire \
          -- -max_total_time=180

  'manticore_protocol_device_id_DeviceId__resp_to_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::device_id::DeviceId` with `resp_to_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_device_id_DeviceId__resp_to_wire \
          -- -max_total_time=180

  'manticore_protocol_device_info_DeviceInfo__req_to_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::device_info::DeviceInfo` with `req_to_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_device_info_DeviceInfo__req_to_wire \
          -- -max_total_time=180

  'manticore_protocol_device_info_DeviceInfo__req_from_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::device_info::DeviceInfo` with `req_from_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_device_info_DeviceInfo__req_from_wire \
          -- -max_total_time=180

  'manticore_protocol_device_info_DeviceInfo__resp_from_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::device_info::DeviceInfo` with `resp_from_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_device_info_DeviceInfo__resp_from_wire \
          -- -max_total_time=180

  'manticore_protocol_device_info_DeviceInfo__resp_to_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::device_info::DeviceInfo` with `resp_to_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_device_info_DeviceInfo__resp_to_wire \
          -- -max_total_time=180

  'manticore_protocol_device_uptime_DeviceUptime__req_to_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::device_uptime::DeviceUptime` with `req_to_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_device_uptime_DeviceUptime__req_to_wire \
          -- -max_total_time=180

  'manticore_protocol_device_uptime_DeviceUptime__req_from_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::device_uptime::DeviceUptime` with `req_from_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_device_uptime_DeviceUptime__req_from_wire \
          -- -max_total_time=180

  'manticore_protocol_device_uptime_DeviceUptime__resp_from_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::device_uptime::DeviceUptime` with `resp_from_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_device_uptime_DeviceUptime__resp_from_wire \
          -- -max_total_time=180

  'manticore_protocol_device_uptime_DeviceUptime__resp_to_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::device_uptime::DeviceUptime` with `resp_to_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_device_uptime_DeviceUptime__resp_to_wire \
          -- -max_total_time=180

  'manticore_protocol_firmware_version_FirmwareVersion__req_to_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::firmware_version::FirmwareVersion` with `req_to_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_firmware_version_FirmwareVersion__req_to_wire \
          -- -max_total_time=180

  'manticore_protocol_firmware_version_FirmwareVersion__req_from_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::firmware_version::FirmwareVersion` with `req_from_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_firmware_version_FirmwareVersion__req_from_wire \
          -- -max_total_time=180

  'manticore_protocol_firmware_version_FirmwareVersion__resp_from_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::firmware_version::FirmwareVersion` with `resp_from_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_firmware_version_FirmwareVersion__resp_from_wire \
          -- -max_total_time=180

  'manticore_protocol_firmware_version_FirmwareVersion__resp_to_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::firmware_version::FirmwareVersion` with `resp_to_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_firmware_version_FirmwareVersion__resp_to_wire \
          -- -max_total_time=180

  'manticore_protocol_request_counter_RequestCounter__req_to_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::request_counter::RequestCounter` with `req_to_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_request_counter_RequestCounter__req_to_wire \
          -- -max_total_time=180

  'manticore_protocol_request_counter_RequestCounter__req_from_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::request_counter::RequestCounter` with `req_from_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_request_counter_RequestCounter__req_from_wire \
          -- -max_total_time=180

  'manticore_protocol_request_counter_RequestCounter__resp_from_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::request_counter::RequestCounter` with `resp_from_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_request_counter_RequestCounter__resp_from_wire \
          -- -max_total_time=180

  'manticore_protocol_request_counter_RequestCounter__resp_to_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::request_counter::RequestCounter` with `resp_to_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_request_counter_RequestCounter__resp_to_wire \
          -- -max_total_time=180

  'manticore_protocol_reset_counter_ResetCounter__req_to_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::reset_counter::ResetCounter` with `req_to_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_reset_counter_ResetCounter__req_to_wire \
          -- -max_total_time=180

  'manticore_protocol_reset_counter_ResetCounter__req_from_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::reset_counter::ResetCounter` with `req_from_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_reset_counter_ResetCounter__req_from_wire \
          -- -max_total_time=180

  'manticore_protocol_reset_counter_ResetCounter__resp_from_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::reset_counter::ResetCounter` with `resp_from_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_reset_counter_ResetCounter__resp_from_wire \
          -- -max_total_time=180

  'manticore_protocol_reset_counter_ResetCounter__resp_to_wire':
    runs-on: ubuntu-latest
    name: 'Fuzz `manticore::protocol::reset_counter::ResetCounter` with `resp_to_wire.rs`'
    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install `cargo fuzz`
      run: cargo install cargo-fuzz
    - name: `cargo fuzz run --release --sanitizer address`
      run: |
        cargo +nightly fuzz run \
          --release --sanitizer address \
          manticore_protocol_reset_counter_ResetCounter__resp_to_wire \
          -- -max_total_time=180

