// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// NOTE: This file is autogenerated by:
// $ util/new_protocol_target.py device_id::DeviceIdRequest

#![no_main]

use libfuzzer_sys::fuzz_target;

use manticore::protocol::ToWire;
use manticore::protocol::device_id::DeviceIdRequest;

fuzz_target!(|data: DeviceIdRequest| {
    let mut out = [0u8; 1024];
    let _ = data.to_wire(&mut &mut out[..]);
});

