// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// NOTE: This file is autogenerated by:
// $ util/new_protocol_target.py --target-templates from_wire -- device_id::DeviceIdResponse

#![no_main]

use libfuzzer_sys::fuzz_target;

use manticore::mem::BumpArena;
use manticore::protocol::wire::FromWire;
use manticore::protocol::device_id::DeviceIdResponse;

fuzz_target!(|data: &[u8]| {
    let mut arena = vec![0; data.len()];
    let arena = BumpArena::new(&mut arena);
    let mut data = data;
    let _ = DeviceIdResponse::from_wire(&mut data, &arena);
});

