// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// NOTE: This file is autogenerated by:
// $ util/new_protocol_target.py capabilities::DeviceCapabilitiesRequest

#![no_main]

use libfuzzer_sys::fuzz_target;

use manticore::protocol::wire::FromWire;
use manticore::protocol::capabilities::DeviceCapabilitiesRequest;

fuzz_target!(|data: &[u8]| {
    let mut data = data;
    let _ = DeviceCapabilitiesRequest::from_wire(&mut data);
});

