// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// NOTE: This file is autogenerated by:
// $ util/new_protocol_target.py --target-templates deserialize serialize_fuzz_safe -- device_info::DeviceInfoResponse<'static>

#![no_main]

use libfuzzer_sys::fuzz_target;

use manticore::protocol::FromWire;
use manticore::protocol::device_info::DeviceInfoResponse;

fuzz_target!(|data: &[u8]| {
    let mut data = data;
    let _ = DeviceInfoResponse<'static>::from_wire(&mut data);
});

