// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// NOTE: This file is autogenerated by:
// $ util/new_protocol_target.py --target-templates serialize_fuzz_safe -- firmware_version::FirmwareVersionResponse<'static>

#![no_main]

use libfuzzer_sys::fuzz_target;

use manticore::protocol::FuzzSafe;
use manticore::protocol::Serialize;
use manticore::protocol::firmware_version::FirmwareVersionResponse;

fuzz_target!(|data: <FirmwareVersionResponse<'static> as FuzzSafe>::Safe| {
    let mut out = [0u8; 1024];
    let data = data.as_ref();
    let _ = data.serialize(&mut &mut out[..]);
});

