// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// NOTE: This file is autogenerated by:
// $ util/new_protocol_target.py firmware_version::FirmwareVersionRequest

#![no_main]

use libfuzzer_sys::fuzz_target;

use manticore::protocol::Serialize;
use manticore::protocol::firmware_version::FirmwareVersionRequest;

fuzz_target!(|data: FirmwareVersionRequest| {
    let mut out = [0u8; 1024];
    let _ = data.serialize(&mut &mut out[..]);
});
