// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// NOTE: This file is autogenerated by:
// $ util/new_protocol_target.py firmware_version::FirmwareVersionResponse --skip-traits ToWire

#![no_main]

use libfuzzer_sys::fuzz_target;

use manticore::protocol::FromWire;
use manticore::protocol::firmware_version::FirmwareVersionResponse;

fuzz_target!(|data: &[u8]| {
    let mut data = data;
    let _ = FirmwareVersionResponse::from_wire(&mut data);
});
