// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// NOTE: This file is autogenerated by:
// $ util/new_protocol_target.py request_counter::RequestCounterRequest

#![no_main]

use libfuzzer_sys::fuzz_target;

use manticore::protocol::wire::ToWire;
use manticore::protocol::request_counter::RequestCounterRequest;

fuzz_target!(|data: RequestCounterRequest| {
    let mut out = [0u8; 1024];
    let _ = data.to_wire(&mut &mut out[..]);
});

